version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
